name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile - Main
        run: |
          docker build -t docker.images/main:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner - Main
        uses: aquasecurity/trivy-action@master
        with:
          ignore-unfixed: true
          image-ref: 'docker.images/main:${{ github.sha }}'
#          format: 'sarif'
#          output: 'trivy-results-main.sarif'


#      - name: Upload Trivy scan results to GitHub Security tab - Main
#        uses: github/codeql-action/upload-sarif@v2
#        if: always()
#        with:
#          sarif_file: 'trivy-results-main.sarif'
#          category: 'main file scan'

      - name: Build an image from Dockerfile - Proxy
        run: |
          docker build -t docker.images/proxy:${{ github.sha }} -f proxy/Dockerfile ./proxy

      - name: Run Trivy vulnerability scanner - Proxy
        uses: aquasecurity/trivy-action@master
        with:
          ignore-unfixed: true
          image-ref: 'docker.images/proxy:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results-proxy.sarif'

      - name: Upload Trivy scan results to GitHub Security tab - Proxy
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results-proxy.sarif'
          category: 'proxy file scan'